export const sidebarNavigation = {
    schoolAdmin: [
        { label: 'Главная', icon: 'menu-home', to: '/' },
        {
            label: 'Учебное заведение',
            icon: 'menu-institution',
            to: '/institution',
        },
        { label: 'Расписание', icon: 'menu-schedules', to: '/schedule' },
        { label: 'Чаты', icon: 'menu-chats', to: '/chats' },
        { label: 'База знаний', icon: 'menu-catalog', to: '/catalogues' },
        { label: 'Студенты', icon: 'menu-students', to: '/students' },
        { label: 'Учебные группы', icon: 'menu-groups', to: '/groups' },
        { label: 'Преподаватели', icon: 'menu-staff', to: '/staff' },
        { label: 'Учебные планы', icon: 'menu-plans', to: '/plans' },
        { label: 'Настройки', icon: 'menu-settings', to: '/preferences' },
    ],
    student: [
        { label: 'Главная', icon: 'menu-home', to: '/' },
        { label: 'Расписание', icon: 'menu-schedules', to: '/schedule' },
        { label: 'Задания', icon: 'menu-assignments', to: '/assignments' },
        { label: 'Чаты', icon: 'menu-chats', to: '/chats' },
        { label: 'База знаний', icon: 'menu-catalog', to: '/catalogues' },
        { label: 'Преподаватели', icon: 'menu-staff', to: '/staff' },
        { label: 'Моя группа', icon: 'menu-groups', to: '/mygroup' },
        { label: 'Семестр', icon: 'menu-students', to: '/terms' },
        { label: 'Настройки', icon: 'menu-settings', to: '/preferences' },
    ],
    staff: [
        { label: 'Главная', icon: 'menu-home', to: '/' },
        { label: 'Расписание', icon: 'menu-schedules', to: '/schedule' },
        { label: 'Задания', icon: 'menu-assignments', to: '/assignments' },
        { label: 'Чаты', icon: 'menu-chats', to: '/chats' },
        { label: 'База знаний', icon: 'menu-catalog', to: '/catalogues' },
        { label: 'Студенты', icon: 'menu-students', to: '/students' },
        { label: 'Настройки', icon: 'menu-settings', to: '/preferences' },
    ],
    parent: [
        { label: 'Главная', icon: 'menu-home', to: '/' },
        { label: 'Чаты', icon: 'menu-chats', to: '/chats' },
        { label: 'Настройки', icon: 'menu-settings', to: '/preferences' },
    ],
}
